trained_fold: Neural/InstanceFG
model_name: ${models.model.hparams.predictor}_${models.model.hparams.num_group}
type: local
model:
  _target_: models.instance_feature_group.InstanceFeatureGroup
  hparams:
    predictor: linear
    num_group: 10  
    num_top_group: 1
    weight_gt: 10
    weight_mse: 1
    temperature: 0.1
    hidden_dim: 100
    input_dim: ${datasets.input_dim}
    output_dim: ${output_dim}
    train_mode: ${train_mode.mode}
    rank_loss: ${rank_loss}
    num_layers: 4
    predictor_hidden: 256
